include: package:lint/analysis_options.yaml
linter:
  rules:
    parameter_assignments: true
    prefer_function_declarations_over_variables: false
analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - pubspec.yaml
    - lib/flavors.dart
    - test/**/*
    - test/*
  errors:
    missing_required_param: error
    parameter_assignments: error
    file_names: ignore
    use_setters_to_change_properties: ignore
